### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by dciccale** [beardon/mws-api#53]
Hi, when getting a response as tab-delimited flat file, the body of the response is going through this bit of code in `client.js:137`

```js
if (body.slice(0, 5) !== '<?xml') {
    const result = iconv.decode(new Buffer(body), 'iso-8859-1');
    const metadata = null;

    return { result, metadata };
}
```

The response has German words in it like "Staubbehältervolumen" which after doing the encoding conversion is turned into "StaubbehÃ¤ltervolumen" which is messed up.

Is that decoding necessary for some reason or we could just remove it? I think the default encoding from mws api is already iso-8859-1 but not entirely sure.

*UPDATE*

Checking the raw response headers, I see is already coming as ISO-8859-1

```
headers:
  { server: 'Server',
       date: 'Sun, 11 Dec 2016 19:31:58 GMT',
       'content-type': 'text/plain;charset=ISO-8859-1',
       'content-length': '750',
...
```

so it should be safe to remove that decoding. and leave it as

```js
if (body.slice(0, 5) !== '<?xml') {
    return { result: body, metadata: null };
}
```

**Comment by dciccale** [comment]
Any updates on this? :) I can do a PR with the changes after this issue has been reviewed.

Another possibility is to allow passing an encoding, or a flag if encoding conversion should take place or not.

However if you just inspect the response, the encoding is already ISO-8859-1 that's why I'm asking to just remove the conversion. (Which is what is causing my data to be badly encoded). By just logging the raw response from amazon, the text is as it should be.

**Comment by tyscorp** [comment]
The encoding change was introduced by @dakk in #47.

Do you know the cause of his original issue?

Why does decoding the response body as iso-8859-1 cause your issue if that is indeed the correct encoding?

It seems like if I remove the decoding it will break some responses, but leaving it in will break others.

**Comment by dciccale** [comment]
That's why I think we should not touch encoding. and use the one that is coming by default from amazon. If someone needs to do something with encoding, anyone can post-process the response and have the correct output.

However given that I am now receiving an already post-encoded thing, I can't revert it.

**Comment by dciccale** [comment]
Now I was able to revert it by doing:

```js
const iconv = require('iconv-lite');
console.log(iconv.encode('StaubbehÃ¤ltervolumen', 'iso-8859-1').toString());
// "Staubbehältervolumen"
```

But this is just silly, because now I'm required to bring in iconv dependency, encode it back to iso-8859-1 (default response encoding) and turn the buffer into a string.

I strongly suggest leaving the default response encoding coming from amazon, and leave users to do post-processing/encoding whatever. Encoding is a tough thing to handle, and better not mess with that. :)
