### ISSUE TITLE
MWSClient is not a function

### ISSUE THREAD

**Issue by eriklueth** [beardon/mws-api#57]
Hey guys,
sorry for molesting but I've got a problem using your libary. I'am trying to execute this function on AWS Lambda, but I've getting this error all the time...

> 260870fe-c7c9-11e6-98c9-818bc8b674a1	TypeError: MWSClient is not a function
>     at exports.handler (/var/task/index.js:10:17)

my code is:

```
const MWSClient = require('mws-api');

exports.handler = (event, context, callback) => {

//Check if required variables are given, if not exit
  if (event.accessKeyId && event.secretAccessKey && event.merchantId && event.ReportType) {

    // mws authentication
    const mws = new MWSClient(JSON.parse(JSON.stringify({
      accessKeyId: event.accessKeyId,
      secretAccessKey: event.secretAccessKey,
      merchantId: event.merchantId,
      host: event.MarketplaceURL,
      meta: {
        retry: event.Retry,
        next: event.Next,
        limit: event.Limit
      }
    })));

  mws.Reports.RequestReport(JSON.parse(JSON.stringify({
      ReportType: event.ReportType,
      StartDate: new Date(event.StartDate),
      EndDate: new Date(event.EndDate),
      ReportOptions: event.ReportOptions,
      MarketplaceIdList: event.MarketplaceIdList
    })))
    .then(function(result, metadata) {
      // result
      console.log(JSON.stringify(result));
      console.log(JSON.stringify(metadata));
      context.done(null, result);
    });


  } else {
    callback("ERROR: accessKeyId, secretAccessKey, merchantId missing");
    console.log("ERROR:accessKeyId, secretAccessKey, merchantId missing");
    process.exit(1);
  }

}

```
I would be so thankful if someone can help me :)

**Comment by tyscorp** [comment]
I just tried your code on AWS Lambda and it worked fine. Which version of mws-api are you using?

**Comment by eriklueth** [comment]
lol thats weird... I'am using mws-api@2.1.0 
Was really hard to get it until this point, because first NPM didn't wanted to install it, because node-gyp failed all the time. Than I had to download lots of stuff to get it to work. After that Lambda didn't wanted it, because it was made on Windows, so I had to build everything on EC2, download it and deploy it to Lambda. And now I'am getting this :/

**Comment by tyscorp** [comment]
Did you make sure to use the correct version of node (4.3) on EC2? What happens if you `console.log(MWSClient)`?

**Comment by eriklueth** [comment]
the console.log() gives me:

> { errorNotImplemented: [Function: errorNotImplemented] }

The Node version on the EC2 could be the issue... was using the newest version. Iam going to change it to 4.3 now and build everything again. After that I will give feedback. Thank you for helping until now 👍

**Comment by eriklueth** [comment]
Ok build everything with node 4.3 and it works now :) thank you so much 👍
