### ISSUE TITLE
special characters like Ä, ö, ü

### ISSUE THREAD

**Issue by florianbepunkt** [beardon/mws-api#66]
Thank you for this library. Special characters like ä, ö, ü, etc. are not handled properly… instead ö for example is returned as Ã¶

Any hint how to encode responses right?

**Comment by florianbepunkt** [comment]
I can solve this by basically wrapping each object property in a decodeURIComponent(escape(STRING)) function, but guess it would be nice to have this at library level

**Comment by tyscorp** [comment]
Is this for csv or xml responses?

**Comment by florianbepunkt** [comment]
neither… just using the default settings and

```
this.mws.Orders.ListOrders({
      MarketplaceId: '…',
      LastUpdatedAfter: moment().subtract(120, 'minutes').toDate(),
      OrderStatus: ['Shipped'],
      FulfillmentChannel: ['AFN']
    });
```

**Comment by florianbepunkt** [comment]
Fixed the enconding issue by having a helper function where I can parse relevant data

```
decodeUTF8(string) {
    return decodeURIComponent(escape(string));
}
```

**Comment by tyscorp** [comment]
I'd like to fix this internally but I have no idea what the correct way to do it is. Would `decodeURIComponent(escape())` handle all use-cases?

I've had problems in the past with encoding (#47 #53) and from looking at the source of the official MWS libs they don't seem to do anything special with the encoding.

**Comment by florianbepunkt** [comment]
@tyscorp Not sure if this handles all use-cases… encoding is a bit tricky. Found a good explanation here: http://stackoverflow.com/questions/5396560/how-do-i-convert-special-utf-8-chars-to-their-iso-8859-1-equivalent-using-javasc

**Comment by dciccale** [comment]
@florianbepunkt Could you check the headers of the response coming from your api calls to mws? In the tests I've made, the headers are coming with ISO-8859-1 encoding. But I am using mws-api Europe, maybe the one you are using comes with another encoding.

Normally the mws-api will send the response in the correct encoding so characters are shown correctly. I don't think amazon would respond with broken characters. You should check that the response header is not changing in your code at some point and breaking the characters.

After knowing the encoding we could properly know which transformation (if any) to apply to the output content.

**Comment by dciccale** [comment]
@florianbepunkt doing a `console.log(response)` here https://github.com/beardon/mws-api/blob/master/lib/client.js#L130 should give the response headers

**Comment by florianbepunkt** [comment]
```
"headers": {
      "server": "Server",
      "date": "Fri, 12 May 2017 17:00:01 GMT",
      "content-type": "text/xml",
      "content-length": "7601",
      "connection": "close",
      "x-amz-date": "Fri, 12 May 2017 17:00:01 GMT",
      "x-amzn-authorization": "XXX"
      "x-mws-request-id": "XXX",
      "x-mws-timestamp": "2017-05-12T17:00:00.994Z",
      "x-mws-response-context": "XXX",
      "vary": "Accept-Encoding,User-Agent"
   },
```

**Comment by dciccale** [comment]
Thanks!
Hmm, not able to see encoding here. I'll check again where I saw this so we can be 100% sure that encoding is not being modified in this library.

**Comment by florianbepunkt** [comment]
yes, I was also wondering because there was no encoding specified. any chance you were requesting a csv flat file since specifying encoding would make moe sense there. btw. I'm also using the european endpoint

**Comment by dciccale** [comment]
I am also using EU endpoint. And yes the response I tested was with CSV.

**Comment by dciccale** [comment]
@florianbepunkt I've found something I am doing since quite some time so I am not completely sure if this will solve your issue but give it a try.

```js
const iconv = require('iconv-lite');
const Promise = require('bluebird');

function getMatchingProduct(asinList = []) {
  return mws.Products.GetMatchingProduct({
    MarketplaceId: '....',
    ASINList: asinList
  })
  .then((res) => JSON.stringify(res, null, 2))
  .then((res) => iconv.encode(res, 'ISO-8859-1'))
  .then((buf) => buf.toString())
  .then(parseJson)
  .then(({result}) => (!Array.isArray(result) ? [result] : result));
}

function parseJson(str) {
  return Promise.try(() => JSON.parse(str));
}
```

The important bit is the encoding just let me know if it works for you

**Comment by BarryCarlyon** [comment]
I just ran into this issue.

https://github.com/beardon/mws-api/blob/master/lib/client.js#L113 puts a call into:

>         requestOpts.encoding = 'binary';

Should this not be:

>         requestOpts.encoding = 'utf8';

Or the encoding line ignored/not set?

Why is it binary?

**Comment by dciccale** [comment]
Somehow I am not having any issues at all on this regard while syncing orders from amazon. And I am receiving all data in German which has quite enough of these characters.

I am not sure where to look on this, I'm open to comments/fixes/prs

**Comment by BarryCarlyon** [comment]
I've just flat removed the encoding line (to test) and it avoids me having to do "additional processing"

**Comment by dciccale** [comment]
Apparently not setting the encoding at all, is making the encoding default to utf-8. As I read here https://stackoverflow.com/questions/14855015/getting-binary-content-in-node-js-using-request#comment-50003830

And a possible solution would be setting this to null to basically prevent having pre-defined encoding at all. But right now I have not much time to test it or so.

**Comment by Raidus** [comment]
Using following snippet in a loop worked in my case:


``` javascript
    var fixedstring;
    var badstring = newObj[key];
    try {
      // If the string is UTF-8, this will work and not throw an error.
      fixedstring = decodeURIComponent(escape(badstring));
    } catch (e) {
      // If it isn't, an error will be thrown, and we can asume that we have an ISO string.
      fixedstring = badstring;
    }
```

**Comment by florianbepunkt** [comment]
@tyscorp Okay, @Raidus solution seems to cover every use case… so using the following parseCsv result works fine with all umlauts and other special characters like ß

```
export const mws = new MWSClient({
  host: process.env.AMAZON_HOST,
  accessKeyId: process.env.AMAZON_ACCESS_KEY,
  secretAccessKey: process.env.AMAZON_SECRET,
  merchantId: process.env.AMAZON_MERCHANT_ID,
  meta: {
    retry: true, // retry requests when throttled
    next: true, // auto-paginate
    limit: Infinity, // only get this number of items (NOT the same as MaxRequestsPerPage)
    parseCSVResult: (data) => {
      let encoded;

      try {
        encoded = decodeURIComponent(escape(data));
      } catch (ex) {
        encoded = data;
      } finally {
        return encoded;
      }
    }
  }
});

```
