### ISSUE TITLE
Request signature not matching

### ISSUE THREAD

**Issue by AndrewSkinner** [beardon/mws-api#76]
I am getting the following error:

  `The request signature we calculated does not match the signature you provided. Check your AWS 
  Secret Access Key and signing method. Consult the service documentation for details.`

My code:
```
const mws = new MWSClient({
  accessKeyId: 'myAccessKey',
  secretAccessKey: 'mySecretAccessKey',
  merchantId: 'myMerchantId',
  meta: {
    retry: true,
    next: true,
    limit: Infinity,
  }
})   

mws.Products.GetMatchingProductForId({
    MarketplaceId: 'myMarketPlaceId',
    IdType: 'ISBN',
    IdList: {
      Id: ['9780439708180']
    }
  })
```

Any help would be greatly appreciated.

**Comment by dciccale** [comment]
Isn't the `authToken` missing?

```js
const mws = new MWSClient({
  accessKeyId: 'myAccessKey',
  secretAccessKey: 'mySecretAccessKey',
  merchantId: 'myMerchantId',
  authToken: 'yourAuthToken', // <----
  meta: {
    retry: true,
    next: true,
    limit: Infinity,
  }
})   
```

**Comment by AndrewSkinner** [comment]
I didn't realize I needed one. Looking at the examples given in the documentation an authToken isn't mentioned.

Can you tell me what is the authToken supposed to be?

**Comment by AndrewSkinner** [comment]
I've been continuing to look into this and I can't seem to find out how I can get an auth token for my own seller account. I am working on an application that I will use with my own seller account. I don't have a developer account just my mws enabled seller account.

**Comment by dciccale** [comment]
@AndrewSkinner you're right if this is for your own seller account you don't need to specify the auth token.

There must be something wrong with your keys, or the way the signature is generated on this module.

**Comment by AndrewSkinner** [comment]
It must be with how the signature is getting generated. I decided to use a different library and my keys have worked fine. Thanks for the help :)

**Comment by dciccale** [comment]
@AndrewSkinner which library are you using?

**Comment by AndrewSkinner** [comment]
I'm using devfacet/mws-product
